apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello1-python
  template:
    metadata:
      labels:
        app: hello1-python
    spec:
      containers:
      - name: hello-python
        image: devopspk93/python-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-python1-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: hello1-python   
